name: local_storage_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  storage_api:
    git:
      url: https://github.com/isaacclinton/dart_storage_api.git
    # path: ../storage_api

  hive: ^2.2.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
